name: black-formatter
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.10
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.5
      - name: Install Black
        run: pip install black
      - name: Run formatter check on the entire project.
        run: black --line-length 80 --check .
